#include "ft_libft_printf.h"
#include "libft/libft.h"

int		main(void)
{
	//  printf("---------- c ----------\n");
	// // ft_printf("my printf : [%c]\n", '\0');
	// // dprintf(1, "-- printf : [%c]\n", '\0');
	// dprintf(1, "  %d\n", ft_printf("my printf : [%10c]", 'a'));
	// dprintf(1, "  %d\n", dprintf(1,"-- printf : [%10c]", 'a'));
	// dprintf(1, "  %d\n", ft_printf("my printf : [%-10c]", 'a'));
	// dprintf(1, "  %d\n", dprintf(1,"-- printf : [%-10c]", 'a'));
	printf("---------- s ----------\n");
	// dprintf(1, "  %d\n", ft_printf("1 my printf : [%s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"1 -- printf : [%s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("2 my printf : [%10s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"2 -- printf : [%10s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("6 my printf : [%10.3s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"6 -- printf : [%10.3s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("10 my printf : [%6.3s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"10 -- printf : [%6.3s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("11 my printf : [%4s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"11 -- printf : [%4s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("12 my printf : [%5.10s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"12 -- printf : [%5.10s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("13 my printf : [%10.5s]", "hey"));
	// dprintf(1, "  %d\n", dprintf(1,"13 -- printf : [%10.5s]", "hey"));
	// dprintf(1, "  %d\n", ft_printf("20 my printf : [%2.0s]", "hey"));
	// dprintf(1, "  %d\n", dprintf(1,"20 -- printf : [%2.0s]", "hey"));
	// dprintf(1, "  %d\n", ft_printf("21 my printf : [%1.2s]", "hey"));
	// dprintf(1, "  %d\n", dprintf(1,"21 -- printf : [%1.2s]", "hey"));
	// dprintf(1, "  %d\n", ft_printf("22 my printf : [%3.3s]", "hey"));
	// dprintf(1, "  %d\n", dprintf(1,"22 -- printf : [%3.3s]", "hey"));
	// dprintf(1, "  %d\n", ft_printf("23 my printf : [%10.3s]", "hey"));
	// dprintf(1, "  %d\n", dprintf(1,"23 -- printf : [%10.3s]", "hey"));
	// dprintf(1, "  %d\n", ft_printf("24 my printf : [%3s]", "hey"));
	// dprintf(1, "  %d\n", dprintf(1,"24 -- printf : [%3s]", "hey"));
	// dprintf(1, "  %d\n", ft_printf("3 my printf : [%-10s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"3 -- printf : [%-10s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("7 my printf : [%-10.4s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"7 -- printf : [%-10.4s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("8 my printf : [%-6.4s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"8 -- printf : [%-6.4s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("9 my printf : [%-3.1s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"9 -- printf : [%-3.1s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("14 my printf : [%-3.6s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"14 -- printf : [%-3.6s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("15 my printf : [%-4.10s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"15 -- printf : [%-4.10s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("16 my printf : [%-10.2s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"16 -- printf : [%-10.2s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("17 my printf : [%-1.1s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"17 -- printf : [%-1.1s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("4 my printf : [%.5s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"4 -- printf : [%.5s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("5 my printf : [%.0s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"5 -- printf : [%.0s]", "hello"));
	// dprintf(1, "  %d\n", ft_printf("30 my printf : [%.20s]", "hello"));
	// dprintf(1, "  %d\n", dprintf(1,"30 -- printf : [%.20s]", "hello"));
	dprintf(1, "  %d\n", ft_printf("30 my printf : [%-10s]", NULL));
	dprintf(1, "  %d\n", dprintf(1,"30 -- printf : [%-10s]", NULL));
	// dprintf(1, "  %d\n", ft_printf("31 my printf : [%.20s]%10s%-5s", "hello", "bonjour", "hi"));
	// dprintf(1, "  %d\n", dprintf(1,"31 -- printf : [%.20s]%10s%-5s", "hello", "bonjour", "hi"));
	// dprintf(1, "  %d\n", ft_printf("32 my printf : [%.10s]%10c%-4c", "hello", 'c', 'A'));
	// dprintf(1, "  %d\n", dprintf(1,"32 -- printf : [%.10s]%10c%-4c", "hello", 'c', 'A'));
	// dprintf(1, "-- printf : [%-10s][%5s]\n", "hello", "hi");
	// ft_printf("-- printf : [%20.5s]\n", "hello");
	// dprintf(1, "-- printf : [%20.5s]\n", "hello");
	//ft_printf("%.4s", NULL);
	//dprintf(1, str);
	// printf("\n");
	// printf("---------- d ----------\n");
	// printf("\n");
	//printf("-- print : [%10.3s]\n", "hello");
	//printf("-- print : %10s\n", "hello");
	//printf("print : %10.3s\n", "hello");
	//printf("-print char : [%*.c]", '10', 'A');
	//printf("print char: [%5c] [%10c]\n", 'a', 'y');
	//ft_printf("print string : %s\n", "hello");
	// printf("print nb: %d %c \n", 42, 'a');
	// printf("print string : %s\n", "hello");
	// printf("%c\n", 'a');
	// printf("%10c\n", 't');
	// printf("%-10c\n", 't');
	// printf("%1c\n", 'y');
	// int i = -2147483648;
	// printf("%d\n", i);
	// printf("%d\n", ft_printf("4caractere 1 %12c caractere 2 %12c\n", 'a', 'c'));
	// printf("%d\n", printf("4caractere 1 %12c caractere 2 %12c\n", 'a', 'c'));
	return (0);
}
